name: autograding assignments

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Googletest
      shell: bash
      working-directory: ${{github.workspace}}
      run: |
          wget https://github.com/google/googletest/archive/refs/tags/v1.13.0.tar.gz
          tar xzf v1.13.0.tar.gz 
          ln -s googletest-1.13.0 googletest
    
    - uses: actions/checkout@v3
    - name: build & run
      run: |
        mkdir build && cd build 
        cmake ..
        make
        ./TwoTest